import sys
import os

sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import psycopg2
from config import DB_CONFIG

def insert_locations():
    """Memasukkan data lokasi ke database"""
    locations_data = [
        (1, "MAIN SECURITY HOUSE", "YARD ZONE I - OFFICE"),
        (2, "MOTO CYCLE PARK", "YARD ZONE I - OFFICE"),
        (3, "POWER HOUSE 1", "YARD ZONE I - OFFICE"),
        (4, "WAREHOUSE 1", "YARD ZONE I - OPEN YARD"),
        (5, "CANTEEN 1", "YARD ZONE I - OFFICE"),
        (6, "MUSHOLA", "YARD ZONE I - OFFICE"),
        (7, "ENGINEERING BUILDING", "YARD ZONE I - OFFICE"),
        (8, "FABRICATION SHOP 1", "YARD ZONE I - OPEN YARD"),
        (9, "FABRICATION SHOP 2", "YARD ZONE I - OPEN YARD"),
        (10, "EXT. FABRICATION SHOP 1", "YARD ZONE I - OPEN YARD"),
        (11, "GAS STORAGE 1", "YARD ZONE I - OPEN YARD"),
        (12, "WAREHOUSE 2", "YARD ZONE I - OPEN YARD"),
        (13, "PMT SITE OFFICE 2", "YARD ZONE I - OFFICE"),
        (14, "FIRE STATION", "YARD ZONE I - OFFICE"),
        (15, "COVER STORAGE", "YARD ZONE I - OPEN YARD"),
        (16, "PROJECT SITE OFFICE 2", "YARD ZONE I - OFFICE"),
        (17, "CONTRACTORS OFFICES AREA 1", "YARD ZONE I - OFFICE"),
        (18, "TOILET 1", "YARD ZONE I - OFFICE"),
        (19, "ELECTRODE STORE 1", "YARD ZONE I - OPEN YARD"),
        (20, "ELECTRODE STORE 2", "YARD ZONE I - OPEN YARD"),
        (21, "HAZARDOUS STORAGE 1", "YARD ZONE I - OPEN YARD"),
        (22, "FACILITY STORE", "YARD ZONE I - OPEN YARD"),
        (23, "RIGGING STORE", "YARD ZONE I - OPEN YARD"),
        (24, "SCAFFOLD STORAGE", "YARD ZONE I - OPEN YARD"),
        (25, "HAZARDOUS STORAGE 2", "YARD ZONE I - OPEN YARD"),
        (26, "PROJECT SITE OFFICE 1", "YARD ZONE I - OFFICE"),
        (27, "TOILET 2", "YARD ZONE II - OFFICE"),
        (28, "GAS STORAGE 2", "YARD ZONE I - OPEN YARD"),
        (29, "PIT X-RAY ENCLOSED ( BUNKER )", "YARD ZONE I - OFFICE"),
        (30, "SCRAP AREA 1", "YARD ZONE I - OPEN YARD"),
        (31, "SCRAP AREA 2", "YARD ZONE I - OPEN YARD"),
        (32, "SCRAP AREA 3", "YARD ZONE I - OPEN YARD"),
        (33, "SECURITY TOWER", "YARD ZONE I - OFFICE"),
        (34, "MIDDLE SIDE OPEN YARD (ZONE 1)", "YARD ZONE I - OPEN YARD"),
        (35, "SEA SIDE OPEN YARD (ZONA 1)", "YARD ZONE I - OPEN YARD"),
        (36, "VIP ROOM", "YARD ZONE II - OFFICE"),
        (37, "O&M WORKSHOP", "YARD ZONE II - OPEN YARD"),
        (38, "GANTRY CRANE 10 TON", "YARD ZONE II - OPEN YARD"),
        (39, "GANTRY CRANE 2 X 50 TON", "YARD ZONE II - OPEN YARD"),
        (40, "ATDE OFFICE", "YARD ZONE II - OPEN YARD"),
        (41, "WAREHOUSE 3", "YARD ZONE II - OPEN YARD"),
        (42, "PMT SITE OFFICE 3", "YARD ZONE II - OFFICE"),
        (43, "LIGHT FABRICATION SHOP", "YARD ZONE II - OPEN YARD"),
        (44, "WORKSHOP 1", "YARD ZONE II - OPEN YARD"),
        (45, "WORKSHOP 2", "YARD ZONE II - OPEN YARD"),
        (46, "WORKSHOP 3", "YARD ZONE II - OPEN YARD"),
        (47, "MIDDLE SIDE OPEN YARD (ZONE 2)", "YARD ZONE II - OPEN YARD"),
        (48, "SEA SIDE OPEN YARD (ZONA 2)", "YARD ZONE II - OPEN YARD"),
        (49, "PAINT STORE", "YARD ZONE III - OPEN YARD"),
        (50, "AUTO PLATE BLASTING & PAINTING PLAN II", "YARD ZONE III - OPEN YARD"),
        (51, "BLASTING CHAMBER 1", "YARD ZONE III - OPEN YARD"),
        (52, "BLASTING CHAMBER 2", "YARD ZONE III - OPEN YARD"),
        (53, "BLASTING CHAMBER 3", "YARD ZONE III - OPEN YARD"),
        (54, "BLASTING CHAMBER 4", "YARD ZONE III - OPEN YARD"),
        (55, "BLASTING CHAMBER 5", "YARD ZONE III - OPEN YARD"),
        (56, "ENCLOSED BLASTING PAINTING CHAMBER", "YARD ZONE III - OPEN YARD"),
        (57, "PAINTING A", "YARD ZONE III - OPEN YARD"),
        (58, "PAINTING B", "YARD ZONE III - OPEN YARD"),
        (59, "TOILET 3", "YARD ZONE III - OFFICE"),
        (60, "NEW BLASTING CHAMBER (UNDER CONSTRUCTION)", "YARD ZONE III - OPEN YARD"),
        (61, "POWER HOUSE 3", "YARD ZONE III - OFFICE"),
        (62, "SEA SIDE OPEN YARD (ZONA 3)", "YARD ZONE III - OPEN YARD"),
        (63, "SITE CONTRACTORS OFFICE 2", "YARD ZONE III - OFFICE"),
        (64, "POWER HOUSE 2", "YARD ZONE III - OFFICE"),
        (65, "CAFETERIA 1", "YARD ZONE III - OFFICE"),
        (66, "GUARD HOUSE 2", "YARD ZONE III - OFFICE"),
        (67, "IYM OFFICE", "YARD ZONE III - OFFICE"),
        (68, "CAFETERIA 2", "YARD ZONE III - OFFICE"),
        (69, "STAFF CANTEEN 2", "YARD ZONE III - OFFICE"),
        (70, "CLIENT OFFICE", "YARD ZONE III - OFFICE"),
        (71, "WORKSHOP 4", "YARD ZONE III - OPEN YARD"),
        (72, "WORKSHOP 5", "YARD ZONE III - OPEN YARD"),
        (73, "MOTOR CYCLE PARK B", "YARD ZONE III - OFFICE"),
        (74, "TOILET 4", "YARD ZONE III - OFFICE"),
        (75, "FRON TSIDE OPEN YARD (ZONE 3)", "YARD ZONE III - OPEN YARD"),
        (76, "MIDDLE SIDE OPEN YARD (ZONE 3)", "YARD ZONE III - OPEN YARD"),
        (77, "SEA SIDE OPEN YARD (ZONA 3)", "YARD ZONE III - OPEN YARD"),
        (78, "GUARD HOUSE 4", "YARD ZONE IV - OFFICE"),
        (79, "NORTH YARD OFFICE", "YARD ZONE IV - OFFICE"),
        (80, "TRAINING CENTRE", "YARD ZONE IV - OFFICE"),
        (81, "MEDICAL CENTRE", "YARD ZONE IV - OFFICE"),
        (82, "WELDING CENTRE", "YARD ZONE IV - OPEN YARD"),
        (83, "TOILET 5", "YARD ZONE IV - OFFICE"),
        (84, "FACILITY STORAGE", "YARD ZONE IV - OPEN YARD"),
        (85, "GUARD HOUSE 5", "YARD ZONE IV - OFFICE"),
        (86, "PLN STATION", "YARD ZONE IV - OPEN YARD"),
        (87, "TOILET 6", "YARD ZONE IV - OFFICE"),
        (88, "WORKSHOP 6", "YARD ZONE IV - OPEN YARD"),
        (89, "WORKSHOP 7", "YARD ZONE IV - OPEN YARD"),
        (90, "WORKSHOP 8", "YARD ZONE IV - OPEN YARD"),
        (91, "WORKSHOP 9", "YARD ZONE IV - OPEN YARD"),
        (92, "GANTRY CRANE 50 TON", "YARD ZONE IV - OPEN YARD"),
        (93, "POWER HOUSE 4", "YARD ZONE IV - OFFICE"),
        (94, "SCRAP AREA", "YARD ZONE IV - OPEN YARD"),
        (95, "PAINT STORE", "YARD ZONE IV - OPEN YARD"),
        (96, "COVERED STORAGE & YARD", "YARD ZONE IV - OPEN YARD"),
        (97, "CAFETERIA 3", "YARD ZONE IV - OFFICE"),
        (98, "SITE OFFICE", "YARD ZONE IV - OFFICE"),
        (99, "OPEN YARD (ZONE IV)", "YARD ZONE IV - OPEN YARD"),
        (100, "BLASTING CHAMBER 6", "YARD ZONE V - OPEN YARD"),
        (101, "BLASTING CHAMBER 7", "YARD ZONE V - OPEN YARD"),
        (102, "DIESEL TANK", "YARD ZONE I - OPEN YARD"),
        (103, "WELD/TEST SHOP", "YARD ZONE V - OPEN YARD"),
        (104, "EMPTY GAS STORAGE", "YARD ZONE III - OPEN YARD"),
        (105, "RUBBISH STORAGE", "YARD ZONE V - OPEN YARD"),
        (106, "GUARD HOUSE 3", "YARD ZONE V - OFFICE"),
        (107, "OPEN YARD (ZONE V)", "YARD ZONE V - OPEN YARD"),
        (108, "WOODGROUP", "OUTSIDE - OFFICE"),
        (109, "PETROTEKNO CILEGON", "OUTSIDE - OFFICE"),
        (110, "BSTC", "OUTSIDE - OFFICE"),
        (111, "LAY DOWN AREA", "YARD ZONE II - OPEN YARD"),
        (112, "GATE 7", "YARD ZONE V - OPEN YARD"),
        (113, "DSAW", "OUTSIDE - OFFICE"),
        (114, "SINGAPORE - ADMIRALTY YARD 4", "OUTSIDE - OPEN YARD"),
        (115, "MARINE HOUSE", "YARD ZONE I - OPEN YARD"),
        (116, "PICKLING CHAMBER", "YARD ZONE III - OPEN YARD"),
        (117, "WAREHOUSE 5", "YARD ZONE IV - OPEN YARD"),
        (118, "QC OFFICE CONTAINER", "YARD ZONE II - OFFICE"),
        (119, "MAIN OFFICE", "YARD ZONE I - OFFICE"),
        (120, "TOYO", "OUTSIDE - OFFICE"),
        (121, "CLADTEK", "OUTSIDE - OFFICE"),
        (122, "LAY DOWN WEST YARD", "YARD ZONE V - OPEN YARD"),
        (123, "SMTC - BATAM", "OUTSIDE - OFFICE"),
        (124, "SMTC - SINGAPORE", "OUTSIDE - OFFICE"),
        (125, "MAIN DECK", "SAY"),
        (126, "CABLE DECK", "SAY"),
        (127, "UTILITY DECK", "SAY"),
        (128, "ROOF DECK", "SAY"),
        (129, "UPPER GRILLAGE", "SAY"),
        (130, "PIPE SHOP 1", "SAY"),
        (131, "SS SHOP", "SAY"),
        (132, "PIPE SHOP 4", "SAY"),
        (133, "LAY DOWN AREA", "SAY"),
        (134, "SMTC - BATAM", "OUTSIDE"),
        (135, "SMTC - SINGAPORE", "OUTSIDE"),
        (136, "SINGAPORE - PIONEER YARD", "OUTSIDE - OPEN YARD"),
        (137, "LOWER GRILLAGE", "SAY"),
        (138, "Online Meeting", "OUTSIDE - OPEN YARD"),
        (139, "Double Bottom", "TBY"),
        (140, "Lower Mega Block", "TBY"),
        (141, "Upper Mega Block", "TBY"),
        (142, "Upper Converter Hull", "TBY"),
        (143, "Topside Main Steel Extension", "TBY"),
        (144, "SF STEEL STOCK YARD (PHASE-2)", "TBY - OPEN YARD"),
        (145, "BLOCK PRE-ERECTION AREA (PHASE-3A)", "TBY - OPEN YARD"),
        (146, "LSF", "SAY"),
        (147, "BAY 1 PART 1", "TBY"),
        (148, "BAY 2 PART 1", "TBY"),
        (149, "BAY 3 PART 1", "TBY"),
        (150, "BAY 4 PART 1", "TBY"),
        (151, "BAY 5 PART 1", "TBY"),
        (152, "PHASE 3A", "TBY"),
        (153, "400 Ton", "TBY"),
        (154, "YST-01", "TBY"),
        (155, "BAY 1 PART 2", "TBY"),
        (156, "BAY 2 PART 2", "TBY"),
        (157, "BAY 3 PART 2", "TBY"),
        (158, "BAY 4 PART 2", "TBY"),
        (159, "BAY 5 PART 2", "TBY"),
        (160, "PHASE 3B", "TBY"),
        (161, "600 Ton", "TBY"),
        (162, "YST-17", "TBY"),
        (163, "BAY 1 PART 3", "TBY"),
        (164, "BAY 2 PART 3", "TBY"),
        (165, "BAY 3 PART 3", "TBY"),
        (166, "BAY 4 PART 3", "TBY"),
        (167, "BAY 5 PART 3", "TBY"),
        (168, "Special Structure Workshop", "TBY"),
        (169, "EH-04", "TBY"),
        (170, "Steel Stock Yard", "TBY"),
        (171, "BAY 1 PART 4", "TBY"),
        (172, "BAY 2 PART 4", "TBY"),
        (173, "BAY 3 PART 4", "TBY"),
        (174, "BAY 4 PART 4", "TBY"),
        (175, "Auto Blasting Chamber", "TBY"),
        (176, "EH-05", "TBY"),
        (177, "300 Ton", "TBY"),
        (178, "BAY 1 PART 5", "TBY"),
        (179, "BAY 2 PART 5", "TBY"),
        (180, "BAY 3 PART 5", "TBY"),
        (181, "BAY 4 PART 5", "TBY"),
        (182, "BAY 5 PART 5", "TBY"),
        (183, "YST-05", "TBY"),
        (184, "YST-19", "TBY"),
        (185, "Panel Line", "PY"),
        (186, "Area A6", "PY"),
        (187, "Area CNTB", "PY"),
        (188, "GAMMA BLOCK", "YARD ZONE I - OFFICE"),
        (189, "Profile Shop", "PY"),
        (190, "NC Shop", "PY"),
        (191, "LAND SIDE OPEN YARD", "YARD ZONE I"),
        (192, "OPEN WORKSHOP", "YARD ZONE I"),
        (193, "WAREHOUSE 4", "YARD ZONE III - OPEN YARD"),
        (194, "LAYDOWN STORAGE MATERIAL", "YARD ZONE III"),
        (195, "MECHANIC WORKSHOP", "YARD ZONE III"),
        (196, "ELECTRICAL WORKSHOP", "YARD ZONE III"),
        (197, "PT. HGM", "OUTSIDE")
    ]
    
    conn = None
    try:
        conn = psycopg2.connect(**DB_CONFIG)
        cur = conn.cursor()
        
        # Hapus data lama (opsional)
        cur.execute("TRUNCATE locations RESTART IDENTITY CASCADE")
        
        # Insert data baru
        for loc in locations_data:
            cur.execute("""
                INSERT INTO locations (id_location, location_name, description)
                VALUES (%s, %s, %s)
                ON CONFLICT (id_location) DO UPDATE 
                SET location_name = EXCLUDED.location_name,
                    description = EXCLUDED.description,
                    updated_at = CURRENT_TIMESTAMP
            """, loc)
        
        conn.commit()
        print(f"✅ Berhasil memasukkan {len(locations_data)} data lokasi!")
        
        # Reset sequence
        cur.execute("SELECT setval('locations_id_location_seq', (SELECT MAX(id_location) FROM locations))")
        conn.commit()
        
    except Exception as e:
        if conn:
            conn.rollback()
        print(f"❌ Error: {e}")
    finally:
        if conn:
            conn.close()

if __name__ == "__main__":
    insert_locations()