"use client";

import { useState, useEffect } from "react";
import { useRouter, useParams } from "next/navigation";
import {
    FileText,
    Calendar,
    MapPin,
    Loader2,
    ArrowLeft,
    Eye,
    Building2,
    User,
    CheckCircle,
    XCircle,
    Clock,
    Camera,
    X,
    ChevronDown,
    ChevronUp,
    Package,
    Laptop,
    Tag,
    QrCode,
    FileSpreadsheet,
    RefreshCw,
    Download,
    TrendingUp,
    PieChart,
} from "lucide-react";
import * as XLSX from "xlsx";
import Swal from "sweetalert2";
import LayoutDashboard from "../../components/LayoutDashboard";
import ProtectedPage from "../../components/ProtectedPage";
import API_BASE_URL from "../../../config/api";

export default function ReportDetailPage() {
    const router = useRouter();
    const params = useParams();
    const reportId = params.id;

    const [report, setReport] = useState(null);
    const [items, setItems] = useState([]);
    const [loading, setLoading] = useState(true);
    const [selectedItem, setSelectedItem] = useState(null);
    const [mounted, setMounted] = useState(false);
    const [isExporting, setIsExporting] = useState(false);
    const [expandedItems, setExpandedItems] = useState(false);

    useEffect(() => {
        setMounted(true);
        fetchReport();
    }, [reportId]);

    const fetchReport = async () => {
        setLoading(true);
        try {
            const response = await fetch(`${API_BASE_URL}/api/reports/${reportId}`);
            const result = await response.json();
            if (result.success) {
                setReport(result.data);
                setItems(result.items || []);
            } else {
                throw new Error(result.error || "Failed to load report");
            }
        } catch (error) {
            console.error("Error fetching report:", error);
            Swal.fire({ title: "Error!", text: error.message, icon: "error" });
        } finally {
            setLoading(false);
        }
    };

    const formatDate = (dateString) => {
        if (!dateString) return "-";
        return new Date(dateString).toLocaleDateString("id-ID", {
            day: "numeric",
            month: "long",
            year: "numeric",
        });
    };

    const formatDateTime = (dateString) => {
        if (!dateString) return "-";
        return new Date(dateString).toLocaleString("id-ID", {
            day: "numeric",
            month: "short",
            year: "numeric",
            hour: "2-digit",
            minute: "2-digit",
        });
    };

    const getTypeIcon = (type) => {
        if (type === "Device") return <Laptop className="w-4 h-4 text-blue-600" />;
        return <Package className="w-4 h-4 text-emerald-600" />;
    };

    const getTypeBadge = (type) => {
        if (type === "Device") return "badge-device";
        return "badge-material";
    };

    const getSuccessRateColor = (rate) => {
        if (rate >= 80) return "#10b981";
        if (rate >= 60) return "#f59e0b";
        return "#ef4444";
    };

    const getStatusBadge = (rate) => {
        if (rate >= 80) return "badge-success";
        if (rate >= 60) return "badge-warning";
        return "badge-danger";
    };

    const handleShowDetail = (item) => setSelectedItem(item);

    const handleExportExcel = async () => {
        if (!items.length) return;
        setIsExporting(true);
        try {
            const summaryData = [
                ["ASSET VALIDATION REPORT"],
                ["Generated:", new Date().toLocaleString()],
                ["Report Code:", report?.report_code || "N/A"],
                ["Report Name:", report?.report_name || "N/A"],
                ["Report Date:", formatDate(report?.report_date)],
                ["Generated By:", report?.generated_by_name || "System"],
                [],
                ["SUMMARY STATISTICS"],
                ["Total Scans", report?.total_scans || 0],
                ["Valid Scans", report?.valid_scans || 0],
                ["Error Scans", report?.error_scans || 0],
                ["Pending Scans", report?.pending_scans || 0],
                ["Success Rate", `${report?.success_rate}%`],
                ["Total Assets", report?.total_assets || 0],
                ["Devices", report?.devices_count || 0],
                ["Materials", report?.materials_count || 0],
                ["Locations", report?.locations_count || 0],
                ["Departments", report?.departments_count || 0],
                ["Projects", report?.projects_count || 0],
                [],
                ["ASSETS DETAILS"],
                [],
                ["No.", "Asset Code", "Asset Name", "Type", "Brand/Vendor", "Serial/Code", "Project", "Department", "Receiver", "Location", "Validated At"],
            ];
            items.forEach((item, index) => {
                summaryData.push([
                    index + 1,
                    item.asset_code || "-",
                    item.asset_name || "-",
                    item.category || "-",
                    item.brand || item.vendor || "-",
                    item.serial_number || item.scan_code || "-",
                    item.project_name || "-",
                    item.department_name || "-",
                    item.receiver_name || "-",
                    item.location_name || "-",
                    formatDateTime(item.validated_at),
                ]);
            });
            const ws = XLSX.utils.aoa_to_sheet(summaryData);
            ws["!cols"] = [{ wch: 6 }, { wch: 18 }, { wch: 30 }, { wch: 12 }, { wch: 20 }, { wch: 25 }, { wch: 20 }, { wch: 20 }, { wch: 20 }, { wch: 20 }, { wch: 22 }];
            const wb = XLSX.utils.book_new();
            XLSX.utils.book_append_sheet(wb, ws, "Report Details");
            const timestamp = new Date().toISOString().slice(0, 19).replace(/[:]/g, "-");
            XLSX.writeFile(wb, `report_${report?.report_code}_${timestamp}.xlsx`);
            Swal.fire({ title: "Success!", text: "Excel report exported successfully", icon: "success", timer: 2000, showConfirmButton: false });
        } catch (error) {
            Swal.fire({ title: "Error!", text: "Failed to export Excel file", icon: "error" });
        } finally {
            setIsExporting(false);
        }
    };

    if (!mounted) {
        return (
            <ProtectedPage>
                <LayoutDashboard activeMenu={3}>
                    <div className="min-h-screen flex items-center justify-center">
                        <Loader2 className="w-8 h-8 animate-spin text-blue-600" />
                    </div>
                </LayoutDashboard>
            </ProtectedPage>
        );
    }

    const displayedItems = expandedItems ? items : items.slice(0, 10);

    return (
        <ProtectedPage>
            <LayoutDashboard activeMenu={3}>
                <style>{`
          @import url('https://fonts.googleapis.com/css2?family=DM+Sans:opsz,wght@9..40,400;9..40,500;9..40,600;9..40,700&family=DM+Mono:wght@400;500&display=swap');
          .rd-root { font-family: 'DM Sans', sans-serif; }
          .rd-root * { box-sizing: border-box; }

          .vv-card {
            background: #ffffff;
            border-radius: 16px;
            box-shadow: 0 4px 6px -1px rgba(0,0,0,0.1), 0 2px 4px -1px rgba(0,0,0,0.06);
            transition: box-shadow 0.2s ease;
          }

          .ai-section {
            background: #ffffff;
            border-radius: 18px;
            border: 1px solid #e5e7eb;
            box-shadow: 0 1px 4px rgba(0,0,0,0.06);
            overflow: hidden;
          }

          .ai-th {
            padding: 10px 14px;
            font-size: 11px;
            font-weight: 700;
            color: #6b7280;
            text-transform: uppercase;
            letter-spacing: 0.07em;
            background: #f9fafb;
            white-space: nowrap;
            border-bottom: 1px solid #e5e7eb;
          }
          .ai-td {
            padding: 13px 14px;
            font-size: 13px;
            color: #374151;
            border-top: 1px solid #f3f4f6;
            vertical-align: middle;
          }
          .ai-row { cursor: pointer; transition: background 0.1s; }
          .ai-row:hover { background: #f8faff; }

          .badge-device { background: #dbeafe; color: #1d4ed8; border: 1px solid #bfdbfe; }
          .badge-material { background: #d1fae5; color: #065f46; border: 1px solid #a7f3d0; }
          .badge-success { background: #d1fae5; color: #065f46; border: 1px solid #a7f3d0; }
          .badge-warning { background: #fed7aa; color: #9a3412; border: 1px solid #fed7aa; }
          .badge-danger { background: #fee2e2; color: #991b1b; border: 1px solid #fecaca; }

          .badge {
            display: inline-flex;
            align-items: center;
            gap: 4px;
            padding: 3px 10px;
            border-radius: 9999px;
            font-size: 11px;
            font-weight: 600;
          }

          .ai-view-btn {
            opacity: 1;
            transition: opacity 0.15s, transform 0.15s;
          }

          .ai-footer {
            display: flex;
            align-items: center;
            justify-content: space-between;
            padding: 10px 18px;
            background: #f9fafb;
            border-top: 1px solid #f3f4f6;
          }

          .ai-empty {
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
            padding: 72px 24px;
            text-align: center;
          }

          .modal-backdrop {
            position: fixed;
            inset: 0;
            background: rgba(0,0,0,0.5);
            display: flex;
            align-items: center;
            justify-content: center;
            z-index: 50;
            padding: 16px;
          }
          .modal-box {
            background: #fff;
            border-radius: 20px;
            max-width: 640px;
            width: 100%;
            max-height: 90vh;
            overflow: hidden;
            box-shadow: 0 25px 50px rgba(0,0,0,0.25);
          }

          .animate-spin { animation: spin 1s linear infinite; }
          @keyframes spin { from{transform:rotate(0deg)} to{transform:rotate(360deg)} }
        `}</style>

                <div className="rd-root space-y-5 max-w-7xl mx-auto px-4 py-2">

                    {/* Page Header */}
                    <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3">
                        <div className="flex items-center gap-3">
                            <button
                                onClick={() => router.push("/reports")}
                                className="flex items-center gap-2 px-4 py-2 text-sm font-medium text-gray-700 bg-white border border-gray-300 rounded-lg hover:bg-gray-50 transition-all"
                            >
                                <ArrowLeft className="w-4 h-4" />
                                Back to Reports
                            </button>
                            <div>
                                <h1 className="text-xl font-bold text-gray-800 flex items-center gap-2">
                                    <FileText className="w-5 h-5 text-blue-600" />
                                    Report Details
                                </h1>
                                <p className="text-sm text-gray-500 mt-0.5">
                                    View detailed asset validation report
                                </p>
                            </div>
                        </div>

                        <div className="flex items-center gap-2">
                            <button
                                onClick={handleExportExcel}
                                disabled={isExporting || items.length === 0}
                                className="flex items-center gap-2 px-4 py-2 text-sm font-medium text-white rounded-lg transition-all disabled:opacity-50"
                                style={{ background: "linear-gradient(135deg,#059669,#10b981)" }}
                            >
                                {isExporting ? (
                                    <><Loader2 className="w-4 h-4 animate-spin" />Exporting...</>
                                ) : (
                                    <><Download className="w-4 h-4" />Export Excel</>
                                )}
                            </button>
                            <button
                                onClick={fetchReport}
                                disabled={loading}
                                className="flex items-center gap-2 px-4 py-2 text-sm font-medium text-gray-700 bg-white border border-gray-300 rounded-lg hover:bg-gray-50 transition-all disabled:opacity-50"
                            >
                                <RefreshCw className={`w-4 h-4 ${loading ? "animate-spin" : ""}`} />
                                {loading ? "Refreshing..." : "Refresh"}
                            </button>
                        </div>
                    </div>

                    {/* Report Info Card */}
                    {report && (
                        <div className="vv-card">
                            <div style={{ padding: "20px 24px", borderBottom: "1px solid #f3f4f6", display: "flex", flexWrap: "wrap", alignItems: "center", justifyContent: "space-between", gap: 16 }}>
                                <div style={{ display: "flex", alignItems: "center", gap: 16 }}>
                                    <div style={{ width: 48, height: 48, borderRadius: 14, background: "#eff6ff", display: "flex", alignItems: "center", justifyContent: "center", flexShrink: 0 }}>
                                        <FileText className="w-6 h-6 text-blue-600" />
                                    </div>
                                    <div>
                                        <h2 style={{ fontSize: 17, fontWeight: 700, color: "#111827" }}>{report.report_name}</h2>
                                        <p style={{ fontFamily: "DM Mono, monospace", fontSize: 12, color: "#9ca3af", marginTop: 2 }}>{report.report_code}</p>
                                    </div>
                                </div>
                                <div style={{ display: "flex", flexWrap: "wrap", gap: 16 }}>
                                    <div style={{ display: "flex", alignItems: "center", gap: 6 }}>
                                        <Calendar style={{ width: 14, height: 14, color: "#9ca3af" }} />
                                        <span style={{ fontSize: 13, color: "#6b7280" }}>{formatDate(report.report_date)}</span>
                                    </div>
                                    <div style={{ display: "flex", alignItems: "center", gap: 6 }}>
                                        <User style={{ width: 14, height: 14, color: "#9ca3af" }} />
                                        <span style={{ fontSize: 13, color: "#6b7280" }}>Generated by {report.generated_by_name || "System"}</span>
                                    </div>
                                </div>
                            </div>

                            {/* KPI stats row */}
                            <div className="grid grid-cols-2 lg:grid-cols-6 divide-x divide-gray-100">
                                {[
                                    { label: "Total Scans", value: report.total_scans || 0, accent: "#2563eb" },
                                    { label: "Valid", value: report.valid_scans || 0, accent: "#10b981" },
                                    { label: "Errors", value: report.error_scans || 0, accent: "#ef4444" },
                                    { label: "Success Rate", value: `${report.success_rate || 0}%`, accent: getSuccessRateColor(report.success_rate || 0) },
                                    { label: "Devices", value: report.devices_count || 0, accent: "#3b82f6" },
                                    { label: "Materials", value: report.materials_count || 0, accent: "#10b981" },
                                ].map((d, i) => (
                                    <div key={i} style={{ display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center", padding: "20px 12px", textAlign: "center" }}>
                                        <p style={{ fontSize: 10, fontWeight: 700, color: "#9ca3af", textTransform: "uppercase", letterSpacing: "0.07em", marginBottom: 8 }}>{d.label}</p>
                                        <span style={{ fontSize: 30, fontWeight: 700, color: d.accent }}>{d.value}</span>
                                    </div>
                                ))}
                            </div>
                        </div>
                    )}

                    {/* Assets Table Card */}
                    <div className="ai-section">
                        <div style={{ padding: "18px 20px", borderBottom: "1px solid #e5e7eb", display: "flex", flexWrap: "wrap", alignItems: "center", justifyContent: "space-between", gap: 12 }}>
                            <div>
                                <h2 style={{ fontSize: 15, fontWeight: 700, color: "#111827", display: "flex", alignItems: "center", gap: 8 }}>
                                    <Package className="w-4 h-4 text-blue-600" />
                                    Assets in this Report
                                </h2>
                                <p style={{ fontSize: 13, color: "#9ca3af", marginTop: 2 }}>{items.length} validated items</p>
                            </div>
                            {items.length > 10 && (
                                <button onClick={() => setExpandedItems(!expandedItems)} className="flex items-center gap-1.5 text-blue-600 hover:text-blue-800 text-sm font-medium">
                                    {expandedItems ? <><ChevronUp className="w-4 h-4" />Show Less</> : <><ChevronDown className="w-4 h-4" />Show All ({items.length})</>}
                                </button>
                            )}
                        </div>

                        {loading ? (
                            <div className="ai-empty">
                                <div className="animate-spin rounded-full h-10 w-10 border-b-2 border-blue-600 mb-4" />
                                <p style={{ fontSize: 13, color: "#6b7280", fontWeight: 500 }}>Loading assets...</p>
                            </div>
                        ) : items.length === 0 ? (
                            <div className="ai-empty">
                                <div style={{ padding: 12, borderRadius: 60, background: "transparent", display: "inline-block", marginBottom: 16 }}>
                                    <Package className="w-10 h-10 text-gray-300" strokeWidth={1.5} />
                                </div>
                                <h3 style={{ fontSize: 14, fontWeight: 500, color: "#6b7280", marginBottom: 4 }}>No assets found</h3>
                                <p style={{ fontSize: 12, color: "#9ca3af" }}>This report has no assets</p>
                            </div>
                        ) : (
                            <div className="overflow-x-auto">
                                <table className="min-w-full">
                                    <thead>
                                        <tr>
                                            <th className="ai-th text-left">Asset Code</th>
                                            <th className="ai-th text-left">Asset Name</th>
                                            <th className="ai-th text-left hidden md:table-cell">Type</th>
                                            <th className="ai-th text-left hidden lg:table-cell">Brand/Vendor</th>
                                            <th className="ai-th text-left hidden xl:table-cell">Serial / Code</th>
                                            <th className="ai-th text-left hidden 2xl:table-cell">Project</th>
                                            <th className="ai-th text-left">Department</th>
                                            <th className="ai-th text-center">Actions</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {displayedItems.map((item) => (
                                            <tr key={item.id_report_item} className="ai-row" onClick={() => handleShowDetail(item)}>
                                                <td className="ai-td">
                                                    <code style={{ fontFamily: "DM Mono, monospace", fontSize: 11, fontWeight: 600, color: "#2563eb" }}>{item.asset_code || "-"}</code>
                                                </td>
                                                <td className="ai-td">
                                                    <div style={{ fontWeight: 600, fontSize: 13, color: "#111827", maxWidth: 180, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" }}>
                                                        {item.asset_name || "-"}
                                                    </div>
                                                </td>
                                                <td className="ai-td hidden md:table-cell">
                                                    <span className={`badge ${getTypeBadge(item.category)}`}>
                                                        {getTypeIcon(item.category)}
                                                        {item.category === "Device" ? "Device" : "Material"}
                                                    </span>
                                                </td>
                                                <td className="ai-td hidden lg:table-cell">
                                                    <span style={{ fontSize: 12, color: "#6b7280" }}>{item.brand || item.vendor || "-"}</span>
                                                </td>
                                                <td className="ai-td hidden xl:table-cell">
                                                    <code style={{ fontFamily: "DM Mono, monospace", fontSize: 11, color: "#6b7280" }}>{item.serial_number || item.scan_code || "-"}</code>
                                                </td>
                                                <td className="ai-td hidden 2xl:table-cell">
                                                    <span style={{ fontSize: 12, color: "#6b7280", maxWidth: 120, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" }}>
                                                        {item.project_name || "-"}
                                                    </span>
                                                </td>
                                                <td className="ai-td">
                                                    <span style={{ fontSize: 12, color: "#6b7280", maxWidth: 120, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" }}>
                                                        {item.department_name || "-"}
                                                    </span>
                                                </td>
                                                <td className="ai-td text-center">
                                                    <button onClick={(e) => { e.stopPropagation(); handleShowDetail(item); }} className="ai-view-btn inline-flex items-center gap-1.5 px-3 py-1.5 text-xs font-semibold text-white rounded-lg" style={{ background: "#2563eb" }}>
                                                        <Eye className="w-3.5 h-3.5" /> View
                                                    </button>
                                                </td>
                                            </tr>
                                        ))}
                                    </tbody>
                                </table>
                            </div>
                        )}

                        {/* Footer */}
                        {!loading && items.length > 0 && (
                            <div className="ai-footer">
                                <p style={{ fontSize: 12, color: "#6b7280" }}>
                                    Showing <span style={{ fontWeight: 600, color: "#374151" }}>{expandedItems ? items.length : Math.min(10, items.length)}</span> of{" "}
                                    <span style={{ fontWeight: 600, color: "#374151" }}>{items.length}</span> assets
                                </p>
                                <p style={{ fontSize: 11, color: "#9ca3af" }}>Generated {formatDateTime(report?.generated_at)}</p>
                            </div>
                        )}
                    </div>
                </div>

                {/* Detail Modal */}
                {selectedItem && (
                    <div className="modal-backdrop" onClick={() => setSelectedItem(null)}>
                        <div className="modal-box" onClick={(e) => e.stopPropagation()}>
                            <div style={{ padding: "18px 20px", borderBottom: "1px solid #f3f4f6", display: "flex", alignItems: "center", justifyContent: "space-between" }}>
                                <div style={{ display: "flex", alignItems: "center", gap: 12 }}>
                                    <div style={{ width: 40, height: 40, borderRadius: 12, background: selectedItem.category === "Device" ? "#eff6ff" : "#ecfdf5", display: "flex", alignItems: "center", justifyContent: "center" }}>
                                        {selectedItem.category === "Device" ? <Laptop className="w-5 h-5 text-blue-600" /> : <Package className="w-5 h-5 text-emerald-600" />}
                                    </div>
                                    <div>
                                        <h2 style={{ fontSize: 15, fontWeight: 700, color: "#111827" }}>Asset Details</h2>
                                        <p style={{ fontFamily: "DM Mono, monospace", fontSize: 11, color: "#9ca3af", marginTop: 2 }}>{selectedItem.asset_code || "-"}</p>
                                    </div>
                                </div>
                                <button onClick={() => setSelectedItem(null)} style={{ padding: 6, borderRadius: 8, background: "transparent", cursor: "pointer", color: "#9ca3af" }}>
                                    <X className="w-5 h-5" />
                                </button>
                            </div>

                            <div style={{ padding: "20px", overflowY: "auto", maxHeight: "calc(90vh - 140px)", display: "flex", flexDirection: "column", gap: 16 }}>
                                <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 12 }}>
                                    {[
                                        { icon: <Tag style={{ width: 14, height: 14, color: "#9ca3af" }} />, label: "Asset Name", value: selectedItem.asset_name || "-" },
                                        { icon: <QrCode style={{ width: 14, height: 14, color: "#9ca3af" }} />, label: selectedItem.category === "Device" ? "Serial Number" : "Scan Code", value: selectedItem.serial_number || selectedItem.scan_code || "-", mono: true },
                                        { icon: <Building2 style={{ width: 14, height: 14, color: "#9ca3af" }} />, label: "Brand / Vendor", value: selectedItem.brand || selectedItem.vendor || "-" },
                                        { icon: <CheckCircle style={{ width: 14, height: 14, color: "#10b981" }} />, label: "Status", value: selectedItem.validation_status === "approved" ? "Validated" : selectedItem.validation_status || "Pending" },
                                    ].map((item, i) => (
                                        <div key={i} style={{ background: "#f9fafb", borderRadius: 12, padding: "12px 14px", border: "1px solid #f3f4f6" }}>
                                            <div style={{ display: "flex", alignItems: "center", gap: 6, marginBottom: 6 }}>
                                                {item.icon}
                                                <p style={{ fontSize: 10, fontWeight: 700, color: "#9ca3af", textTransform: "uppercase", letterSpacing: "0.07em" }}>{item.label}</p>
                                            </div>
                                            <p style={{ fontSize: 13, fontWeight: 600, color: "#111827", fontFamily: item.mono ? "DM Mono, monospace" : "inherit", wordBreak: "break-all" }}>{item.value}</p>
                                        </div>
                                    ))}
                                </div>

                                {selectedItem.specifications && (
                                    <div style={{ background: "#f9fafb", borderRadius: 12, padding: "14px", border: "1px solid #f3f4f6" }}>
                                        <div style={{ display: "flex", alignItems: "center", gap: 6, marginBottom: 8 }}>
                                            <FileText style={{ width: 14, height: 14, color: "#9ca3af" }} />
                                            <p style={{ fontSize: 10, fontWeight: 700, color: "#9ca3af", textTransform: "uppercase", letterSpacing: "0.07em" }}>Specifications</p>
                                        </div>
                                        <p style={{ fontSize: 13, color: "#374151", whiteSpace: "pre-wrap" }}>{selectedItem.specifications}</p>
                                    </div>
                                )}

                                <div style={{ background: "#f9fafb", borderRadius: 12, padding: "14px", border: "1px solid #f3f4f6" }}>
                                    <div style={{ display: "flex", alignItems: "center", gap: 6, marginBottom: 10 }}>
                                        <User style={{ width: 14, height: 14, color: "#9ca3af" }} />
                                        <p style={{ fontSize: 10, fontWeight: 700, color: "#9ca3af", textTransform: "uppercase", letterSpacing: "0.07em" }}>Assignment</p>
                                    </div>
                                    <div style={{ display: "flex", flexDirection: "column", gap: 8 }}>
                                        {[
                                            { label: "Project", value: selectedItem.project_name || "-" },
                                            { label: "Department", value: selectedItem.department_name || "-" },
                                            { label: "Receiver", value: selectedItem.receiver_name || "-" },
                                            { label: "Location", value: selectedItem.location_name || "-" },
                                        ].map((row, i) => (
                                            <div key={i} style={{ display: "flex", alignItems: "center", justifyContent: "space-between" }}>
                                                <span style={{ fontSize: 12, color: "#9ca3af" }}>{row.label}</span>
                                                <span style={{ fontSize: 13, fontWeight: 500, color: "#374151" }}>{row.value}</span>
                                            </div>
                                        ))}
                                    </div>
                                </div>

                                <div style={{ background: "#eff6ff", borderRadius: 12, padding: "14px", border: "1px solid #bfdbfe" }}>
                                    <div style={{ display: "flex", alignItems: "center", gap: 6, marginBottom: 10 }}>
                                        <CheckCircle style={{ width: 14, height: 14, color: "#2563eb" }} />
                                        <p style={{ fontSize: 10, fontWeight: 700, color: "#1d4ed8", textTransform: "uppercase", letterSpacing: "0.07em" }}>Validation Information</p>
                                    </div>
                                    <div style={{ display: "flex", flexDirection: "column", gap: 8 }}>
                                        <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between" }}>
                                            <span style={{ fontSize: 12, color: "#3b82f6" }}>Validated By</span>
                                            <span style={{ fontSize: 13, fontWeight: 600, color: "#1d4ed8" }}>{selectedItem.validated_by_name || selectedItem.validated_by || "System"}</span>
                                        </div>
                                        <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between" }}>
                                            <span style={{ fontSize: 12, color: "#3b82f6" }}>Validated At</span>
                                            <span style={{ fontSize: 13, fontWeight: 600, color: "#1d4ed8" }}>{formatDateTime(selectedItem.validated_at)}</span>
                                        </div>
                                        {selectedItem.unique_code && (
                                            <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between" }}>
                                                <span style={{ fontSize: 12, color: "#3b82f6" }}>Unique Code</span>
                                                <code style={{ fontSize: 11, fontWeight: 600, color: "#1d4ed8", fontFamily: "DM Mono, monospace" }}>{selectedItem.unique_code}</code>
                                            </div>
                                        )}
                                    </div>
                                </div>
                            </div>

                            <div style={{ padding: "14px 20px", borderTop: "1px solid #f3f4f6", display: "flex", justifyContent: "flex-end" }}>
                                <button onClick={() => setSelectedItem(null)} className="inline-flex items-center gap-2 px-5 py-2.5 text-sm font-semibold text-white rounded-xl" style={{ background: "linear-gradient(135deg,#1d4ed8,#2563eb)" }}>
                                    Close
                                </button>
                            </div>
                        </div>
                    </div>
                )}
            </LayoutDashboard>
        </ProtectedPage>
    );
}